version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    env_file: ./.env
  frontend:
    image: roshpenin/foodgram-frontend:latest
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    volumes:
      # - ../frontend/:/app/result_build/
      - ./frontend:/foodgram/result_build/
  backend:
    image: roshpenin/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/foodgram/static/
      - media_value:/foodgram/media/
    depends_on:
      - db
    env_file: ./.env
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  db:
  static_value:
  media_value: